### ISSUE TITLE
Could you please, update the zip file for Android 5.1.1?

### ISSUE THREAD

**Issue by lockevn** [gkraynov/nexus-4-navfix#2]
Google has just release Android 5.1.1 for Nexus 4. Could you please update this patch for it?

I saw that your patch is denied in AOSP and we need to manually patch with your update.zip.

Thank you.

**Comment by sridharpg** [comment]
+1

**Comment by gtklocker** [comment]
:+1:

**Comment by jsotuyod** [comment]
+1

**Comment by jolaviska** [comment]
+1

**Comment by lockevn** [comment]
For more information. I use the prebuilt update.zip with stockROM 5.1 for Mako, not success.
I extracted the SysteUI.apk to manually patch it, not success.
I did the same process with the AOKP, CM, MIUI ROM, in either root/unroot, all failed.

Recent days, I update (OTA) to stockROM 5.1.1, and cannot do anything but wait.

**Comment by gkraynov** [comment]
Unfortunately, I can't continue this little project. Read description for more information.

**Comment by khukuh** [comment]
hope your magic UPDATE.ZIP continue for 5.1.1 , and bring our navbar normal again ..

thanks Bro, GBU
