### ISSUE TITLE
Thanks thread

### ISSUE THREAD

**Issue by gkraynov** [gkraynov/nexus-4-navfix#3]
Unfortunately, I can't continue this little project due to broke of my phone. You can say thanks here for work already done. This could improve my Resume/CV and probably will signal phone manufacturers to review hardware issues more carefully.
Thank you, thanks everybody! I'm happy that you have working phone even on 5.1.0 ROM.

**Comment by IMMatthu** [comment]
Hi Grigoriy,

I made an account to thank you. 

Your fix fully restored my Nexus 4 to a functional state. 

Unfortunately, I've since moved to 5.1.1 and so it seems I will be stuck with a broken navbar, and using pie controls. Nonetheless, I really appreciate the work you've done here!

**Comment by Benibur** [comment]
Thanks !
I managed to install an original 5.0.1 (from the official page here : https://developers.google.com/android/nexus/images), then I flashed the correct update.zip, and that was it.
my phone is born again !
great job.

**Comment by Zashas** [comment]
Huge thanks for your fix. You saved my N4 !
If you ever need someone to test your script with a future update, you can always PM me, I'd be glad to help.

**Comment by ambdeep** [comment]
I know that you have officially retired from this project, but is there any chance you could build this fix for LYV48C or make some sort of tutorial on how to build one myself?

**Comment by talk2om** [comment]
Thanks for your fix.
I tried to follow all the steps mentioned by RavanH, but unfortunately this fix didnt work. Most of the commands for executed with same terminal and phone report, except for one mentioned below.
When I executed......

>>>> adb sideload UPDATE.zip 
(Have downloaded LMY47V/UPDATE.zip, since os is 5.1.1)

My Phone reported

1 Restarting adbd...
2 Finding update package... 
3 Opening update package...
4 Installing update...
5 Updated
	
Was not able to see "Verifying update package..." and "Verifying current system..."

Does this mean, package is not updated properly and hence the issue still persist?
Any pointers would be of great help.

Regards, OM.

**Comment by jeffryT** [comment]
me sirvió por tres días de manera perfecta este FIX , pero luego me falló de la nada esto me hace pensar que hace alta algo , lo aplique en nexus 4 v:5.1.1 , que mas puedo hacer ? ahora lo que esoty haciendo es re instalar firm stock de nuevo y aplicar fix de nuevo a ver cuanto dura , pero la verda es cansado estar en esto sin algo definitivo... creeme que si consigo que dure tiempo el fix te ayudo. gracias de todas formas

**Comment by fmendoza** [comment]
Just tried in my Nexus 4 (5.1.1) and it works. Thanks!

**Comment by ttherapo** [comment]
Thank you for your great work! Any chance making a patch for the new Google firmware? Thanks

**Comment by jinto-kuriakose** [comment]
Huge thanks for your fix. You saved my Nexus4 too.

It worked on 5.1.1 too.

**Comment by vishaldhudum** [comment]
It's not working on my nexus 4 with 5.1.1

**Comment by UkropCanada** [comment]
Didn't work for me on LMY48I and LMY47V (when I reverted back to it)...

**Comment by pejotigrek** [comment]
is there any way to get the patch working with LMY48I? :(

**Comment by gkraynov** [comment]
I will take a look for LMY48I soon. I have no plenty of spare time to follow up on updates immediately :(

**Comment by pejotigrek** [comment]
thanks a lot!

**Comment by Brad3rs** [comment]
Thanks for the nexus navbar fix :) iv'e been using button savior :( ...but now all is well with my phone :) i downgraded it with nexus root toolkit to use it with LMY47V. hopefully you will get around to looking at  LMY48I soon but for now a big thank you :)

**Comment by comeonfox** [comment]
Are the builds supportted by this patch all stock roms, what is the
corresponding builds of cyanogenmod?
2015年8月31日 下午3:23于 "PeeJay" <notifications@github.com>写道：

**Comment by UkropCanada** [comment]
What is the best installation guide for this fix?
Thanks!

**Comment by pejotigrek** [comment]
@UkropCanada copy/push it to the device, boot to recovery [custom recovery works best - Clockwork or better one: TWRP], select flash from ZIP and you're done.

if you're at windows, you can also use Nexus Root Toolkit

**Comment by shuklaalok7** [comment]
Thanks a lot. Worked as a charm for LMY48M. If you need N4 for testing, give a shout to @shuklaalok7.

**Comment by jbollacke** [comment]
Thank you for this fix. `patch.sh` still works. even on the latest cm12.1 nightly. I had to upgrade apktool to v2.0.2 though.

**Comment by bujooo** [comment]
Thanks for fix.
It worked for me, but i had to downgrade to LRX22C (i was on LMY48T).
Here's tutorial i followed, in case someone wants to do same.
http://www.droidviews.com/how-to-downgrade-firmware-on-google-nexus-devices/
And here you can find stock roms.
https://developers.google.com/android/nexus/images
Sadly it can't fix dead zones in other parts of screen...
