### ISSUE TITLE
Any chance of a prebuilt for LMY48I soon?

### ISSUE THREAD

**Issue by RavanH** [gkraynov/nexus-4-navfix#6]
Hi Grigoriy, hope you are doing well :) ... I know you don't have a Nexus 4 anymore so please let me know if you have time to create a prebuilt update.zip for LMY48I and I'll be very happy to test it !

https://dl.google.com/dl/android/aosp/occam-lmy48i-factory-a70487f1.tgz

**Comment by aggiemarine07** [comment]
i agree, any plan on when you can have a pre-built for this version of android so that we dont have security holes in our system due to the patch?

**Comment by gkraynov** [comment]
Hi guys!
I appologise for making you waiting for a patch.
I will take a look into the new image soon.

**Comment by vishaldhudum** [comment]
gkraynov some people like me have no effect on nav bar after installing your update can you help with that please.

**Comment by sband** [comment]
Will be really helpful getting the fix for LMY48I .... thanks

**Comment by gkraynov** [comment]
LMY48M is released

**Comment by RavanH** [comment]
Fantastic ! Goint to patch now...

**Comment by RavanH** [comment]
I think my Nexus 4 is too far gone to be able to tell... Previous patch LMY47V stopped working for me a while back ( see issue #4 ) so it's probably no surprise this update.zip does not do it for me either. 

Hope it still works for others. Can anyone confirm? :)

**Comment by aggiemarine07** [comment]
patch works great! thanks!

**Comment by RavanH** [comment]
Thanks @aggiemarine07 for confirming. And thanks @gkraynov for yet another prebuilt while you do not even have a Nexus4 e anymore!

**Comment by vishaldhudum** [comment]
i don't know why but that patch is not working for me.:(

**Comment by aggiemarine07** [comment]
@vishaldhudum I had to revert/rollback back the previous navfix version, then flash the new factory image from Google (LMY48M), then apply the new navfix.

**Comment by vishaldhudum** [comment]
@aggiemarine07 
i didn't understand what you said but this is what i did
1. flashing latest factory image (LMY48M)
2. installed TWRP recovery
3. tried both methods sideload as well as installing zip through twrp for flashing latest navfix.

But still its not working.

**Comment by aggiemarine07** [comment]
@vishaldhudum These are the steps I did:
1) Run the rollback_update.zip for your current build (mine was LMY47V)
2) Flash the new Factory Image (LMY48M)
3) Run the update.zip navfix for the new build (LMY48M)

I followed the instructions listed on github (http://status301.net/how-to-fix-nexus-4-unresponsive-soft-navigation-menu-buttons/) using CWM. Worked first time, no problems.

In your case I would do the whole process using the LMY47V rollback_update.zip. If that doesnt work then I would try using the LMY48M rollback_update.zip. Im not a developer so this is just a guess. :-/

**Comment by vishaldhudum** [comment]
i thought flashing a rom will disable all changes made by update.zip. If its not that way then i never did rollback_update.zip, @aggiemarine07 i wish we could get an answer from a developer.
and i have also followed those steps earlier when i was on 5.1.0 but that to didn't work.

**Comment by vishaldhudum** [comment]
do anybody know what are those source code files are for?????

**Comment by RavanH** [comment]
@vishaldhudum if the patches do not work for you, either your issue is different or your phone is too far gone. 

As in my case, the different patches have worked for about 7 months until suddenly the issue came  back along with occasional ghost tapping and complete screen freezes. This indicates the underlying hardware problem has become worse and cannot be worked around any more with this patch. Time to get a new touch screen digitizer or a new phone, I'm afraid...

**Comment by vishaldhudum** [comment]
Hmm that could be said, till now i was using gravitybox for increasing navbar height. i will continue with that.
